### ISSUE TITLE
NPC's Disappearing 

### ISSUE THREAD

**Issue by BGHDDevelopment** [JitseB/NPCLib#57]
**Describe the bug**
NPC's keep disappearing randomly when the player joins the server. If they rejoin they normally reappear. 

**NPCLib usage option**
Code: https://hastebin.com/ixumoleyon.java

**NPCLib JAR name**
2.4, LATEST

**Server version**
Spigot 1.8.8 (Custom built, but no real changes from default BuildTools spigot except disabling /pl and /about)

**To Reproduce**
- Join the game and see the NPC not appear

**Expected behavior**
NPC to spawn + NPC nametag to spawn

**Screenshots**
https://photos.bghddevelopment.com/u/17.40.23-12.03.20.png

**Additional context**
This is completely random it can happen on some joins, and not on others. When the player who has the issue rejoins it normally works fine then.

**Comment by JitseB** [comment]
Does the same issue occur if you delay the spawning even more? It might have to do with that the player hasn't "fully" joined yet.

**Comment by BGHDDevelopment** [comment]
I will try delaying the spawning even more tonight and get back to you soon.

**Comment by BGHDDevelopment** [comment]
Changed the delay from 20 to 60, seems to be more reliable now though at points the whole NPC(and holo) does not show up at all unless the player rejoins. Should I delay it more or try something else?

**Comment by A248** [comment]
I have the same error, but I'll try delaying the NPC spawn and see if it works.

**Comment by Mooselk** [comment]
Are you fetching the skin from the MineSkin API every time you load your NPCs?

**Comment by A248** [comment]
@Mooselk yes, the skins are fetched on startup. Skins work fine and are displayed. Even if they didn't, NPC#setSkin(Skin) isn't required – the NPC would just use the default skin.

**Comment by Mooselk** [comment]
I had this issue in the past.  Loading multiple NPCs at once using the Mineskin API would cause most to not load properly, most likely rate limiting.  I got around this by saving the value and signature received and creating a skin that way, only having to fetch the skin once and never again.

**Comment by A248** [comment]
That's not the problem. The NPCs themselves are disappearing. The skins are displayed if the NPCs appear.

**Comment by Mooselk** [comment]
I understand the problem, I'm telling you how I fixed it.

**Comment by JitseB** [comment]
> I had this issue in the past. Loading multiple NPCs at once using the Mineskin API would cause most to not load properly, most likely rate limiting. I got around this by saving the value and signature received and creating a skin that way, only having to fetch the skin once and never again.

That would be a rather strange solution to this problem. Even in @BGHDDevelopment's code, the NPCs objects are only created after the skin has been fetched. Therefore, if the skin would not be fetched before the player joined, it would throw an NPE. If it would be fetched incorrectly, again, a "failed" method would be called, again resulting in a thrown NPE. If the skin data is null, it would be an NPC with a Steve/Alex skin.

Do the NPCs spawn normally if you trigger the spawning on a after login event, e.g. when the player shifts? I could try to do some research into what is causing this issue of in-received packets if this would be the case.

**Comment by A248** [comment]
There are 4 NPCs in my spawn which are made visible 5 seconds after the trigger of the PlayerJoinEvent. However, only some of the NPCs actually show – typically the NPCs in front of the player. The NPCs behind the player are visible when the player turns around.

If the player moves away from the spawn area, away from the NPCs, and returns, all of the NPCs are shown.

**Comment by andrei923** [comment]
can confirm, this also happens for me. (1.8.8).

**Comment by BGHDDevelopment** [comment]
Just following up on this. I am still having the issue I have also tried using other 1.8 jars with the same thing happening.

**Comment by JitseB** [comment]
I'll try to come up with a solution for this problem tonight. I think I'll end up searching for a way to see when the player is fully connected because that seems to be the issue here. The packets aren't accepted by the client thus not showing the NPCs.

**Comment by JitseB** [comment]
Maybe, just maybe, the NPCs aren't shown to the clients because with high ping the player info is removed before they are fully joined. After some testing on Hypixel, I found that their delay to remove the player info is about 10 seconds. So I think it's worth a try.
Testing this is extremely hard for me. I can't simulate a high ping connection on my machine, nor do I have access to a remote server (anymore).
The newest release of NPCLib I'm about to post will include this potential fix. I'll be waiting here to see the results you all can get. (and if I can't finish it tonight, I'll make some time tomorrow night).

**Comment by JitseB** [comment]
https://github.com/JitseB/NPCLib/releases/tag/2.4.2-SNAPSHOT

**Comment by A248** [comment]
My ping to my server never goes over 80 ms, but I still experience this problem. However, I will test the latest release and get back to you with results if anything changes (Note that I'm somewhat busy at the moment so it might be a while before I push the changes and restart the server)

**Comment by JitseB** [comment]
That's fine. Best of luck!

**Comment by BGHDDevelopment** [comment]
From what I can tell it seemed to have fixed it for at least me when I connect. I will keep testing and get some other players on to test as well.

**Comment by JitseB** [comment]
Is the issue still occurring to players?

**Comment by A248** [comment]
I can't reproduce this issue anymore on my test server using NPCLib 2.4.2; as far as I can tell it's fixed. Feel free to close this issue. :)

(I will note that there is a considerably longer / more complex login process with lots of logic running on `PlayerJoinEvent` on my production server. If the problem comes back I'll let you know.)

**Comment by BGHDDevelopment** [comment]
Same seems to be fixed. Thanks for all the hard work.

**Comment by JitseB** [comment]
Hi, I just remembered that you used a timer to make sure the NPC was visible after joining the server. As the delay for removing the player info is set to 10 seconds now, there's no need for this!
One runnable less on your join script. 😛 

Cheers!

**Comment by A248** [comment]
Thanks! I'll make the appropriate changes.

**Comment by Exception426** [comment]
Hey, i had the same issue in the latest version (2.5.1).
I downloaded the 2.5.1 earlier but with the 2.5 it was also asked for help.
